# Generated by Django 5.2.6 on 2025-11-24 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('SE', 'Software Engineering'), ('Management', 'Management'), ('Other', 'Other')], max_length=50)),
                ('complaint_category', models.CharField(choices=[('Academic', 'Academic'), ('Hostel', 'Hostel'), ('Transport', 'Transport'), ('Cafeteria', 'Cafeteria'), ('Other', 'Other')], default='Academic', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending'), ('In Process', 'In Process'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Sent', max_length=20)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
